name: Update Avatar Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-avatar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Updated to use Node.js version 18

      - name: Install dependencies
        run: |
          npm install discord.js dotenv

      - name: Run bot script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}  # Pass the user ID as a secret
        run: |
          node index.js

      - name: Commit and push avatar URL
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add avatar.txt
          git commit -m "Update avatar URL"
          git push
